#### Project: Parkinsons Telemonitoring
#### Name: Kalyan kumar Papani
####             Ayush VimalKumar Patel
####             Miliben Vineshkumar Patel
####             Sirivenni Pati

In [1]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\dpate\anaconda3\lib\site-packages (0.0.3)
Note: you may need to restart the kernel to use updated packages.

#### All import Statements

In [2]:
#import statements
import pandas as pd
from ucimlrepo import fetch_ucirepo
import csv
import numpy as np
import mysql.connector

In [3]:
parkinsons_telemonitoring = fetch_ucirepo(id=189)

In [4]:
x = parkinsons_telemonitoring.data.features
y = parkinsons_telemonitoring.data.features

In [5]:
url = 'https://archive.ics.uci.edu/static/public/189/data.csv'

In [6]:
df = pd.read_csv(url)
df.head()

,subject#,age,sex,test_time,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP,Shimmer,...,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE,motor_UPDRS,total_UPDRS
0,1,72,0,5.6431,0.00662,0.000034,0.00401,0.00317,0.01204,0.02565,...,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006,28.199,34.398
1,1,72,0,12.6660,0.00300,0.000017,0.00132,0.00150,0.00395,0.02024,...,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810,28.447,34.894
2,1,72,0,19.6810,0.00481,0.000025,0.00205,0.00208,0.00616,0.01675,...,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014,28.695,35.389
3,1,72,0,25.6470,0.00528,0.000027,0.00191,0.00264,0.00573,0.02309,...,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277,28.905,35.810
4,1,72,0,33.6420,0.00335,0.000020,0.00093,0.00130,0.00278,0.01703,...,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361,29.187,36.375

#### Data Exploration Task 1

In [7]:
df.isna().any()

subject#         False
age              False
sex              False
test_time        False
Jitter(%)        False
Jitter(Abs)      False
Jitter:RAP       False
Jitter:PPQ5      False
Jitter:DDP       False
Shimmer          False
Shimmer(dB)      False
Shimmer:APQ3     False
Shimmer:APQ5     False
Shimmer:APQ11    False
Shimmer:DDA      False
NHR              False
HNR              False
RPDE             False
DFA              False
PPE              False
motor_UPDRS      False
total_UPDRS      False
dtype: bool

#### Data Exploration Task 3

In [8]:
relevant_feature = 'Jitter(%)'

# Minimum and Maximum
min_value = df[relevant_feature].min()
max_value = df[relevant_feature].max()

# Mean, Median, and Mode
mean_value = df[relevant_feature].mean()
median_value = df[relevant_feature].median()
mode_value = df[relevant_feature].mode()[0]

# Range
range_value = max_value - min_value

# Variance and Standard Deviation
variance_value = df[relevant_feature].var()
sd_value = df[relevant_feature].std()

# 1st, 2nd, and 3rd Quartiles
q1 = df[relevant_feature].quantile(0.25)
q2 = df[relevant_feature].quantile(0.5)
q3 = df[relevant_feature].quantile(0.75)

In [9]:
print(f"Minimum Value: {min_value:.2f}")
print(f"Maximum Value: {max_value:.2f}")
print(f"Mean Value: {mean_value:.2f}")
print(f"Median Value: {median_value:.2f}")
print(f"Mode Value: {mode_value:.2f}")
print(f"Range Value: {range_value:.2f}")
print(f"Variance Value: {variance_value:.2f}")
print(f"Standard Deviation Value: {sd_value:.2f}")
print(f"1st Quartiles Value: {q1:.2f}")
print(f"2nd Quartiles Value: {q2:.2f}")
print(f"3rd Quartiles Value: {q3:.2f}")

Minimum Value: 0.00
Maximum Value: 0.10
Mean Value: 0.01
Median Value: 0.00
Mode Value: 0.00
Range Value: 0.10
Variance Value: 0.00
Standard Deviation Value: 0.01
1st Quartiles Value: 0.00
2nd Quartiles Value: 0.00
3rd Quartiles Value: 0.01

#### Data Exploration Task 4

In [10]:
def FrequencyDistribution(d):
    F = pd.cut(d, bins=10)
    FRC = {}
    CRF = 0; RF = 0
    for i in F:  
        mid_point = (i.left + i.right) / 2
        RF = i.right / len(d)
        CRF += RF
        FRC[mid_point] = [RF, CRF]
    return FRC

fd = FrequencyDistribution(df[relevant_feature])

In [11]:
print(f"Frequency Distribution: {fd}")

Frequency Distribution: {0.0057155: [1.8212765957446808e-06, 0.011907880851064508], 0.0157: [3.5234042553191488e-06, 0.011780391489362331], 0.02565: [5.208510638297872e-06, 0.011537531914894173], 0.07519999999999999: [1.3651063829787234e-05, 0.002044425531914924], 0.045450000000000004: [8.57872340425532e-06, 0.010677191489362045], 0.03555: [6.893617021276596e-06, 0.010684085106383322], 0.09505: [1.7021276595744682e-05, 0.008042025531914545], 0.08515: [1.5336170212765957e-05, 0.00950161702127671], 0.055349999999999996: [1.0263829787234043e-05, 0.010824000000000377], 0.06525: [1.1948936170212765e-05, 0.009648612765957562]}

#### Data Exploration Task 5

In [12]:
def FrequencyDistribution_mean(d):
    F = FrequencyDistribution(d)
    N = 0; D = 0;
    for mid_point, values in F.items():
        RF, CRF = values
        N += mid_point * RF
        D += RF
    Fx = N / D
    return Fx

fdm = FrequencyDistribution_mean(df[relevant_feature])
print(f"Mean of Frequency Distribution: {fdm:.2f}")

Mean of Frequency Distribution: 0.07

#### Data Shaping Task 1

In [13]:
import numpy as np

additional_instances = pd.DataFrame(columns=df.columns)
num_additional_instances = 2000

rows_to_concat = []

for i in range(num_additional_instances):
    random_row = df.sample()
    rows_to_concat.append(random_row)

additional_instances = pd.concat(rows_to_concat, ignore_index=True)
additional_instances.to_csv('new_instances.csv', index=True)
additional_instances.head()

,subject#,age,sex,test_time,Jitter(%),Jitter(Abs),Jitter:RAP,Jitter:PPQ5,Jitter:DDP,Shimmer,...,Shimmer:APQ5,Shimmer:APQ11,Shimmer:DDA,NHR,HNR,RPDE,DFA,PPE,motor_UPDRS,total_UPDRS
0,5,75,0,58.561,0.00450,0.000045,0.00151,0.00277,0.00453,0.06258,...,0.03889,0.06282,0.09089,0.024861,18.138,0.57407,0.67395,0.27477,31.000,40.910
1,28,74,1,48.325,0.00849,0.000044,0.00475,0.00419,0.01425,0.02744,...,0.01386,0.01787,0.04236,0.013310,22.264,0.52173,0.74236,0.20661,31.469,38.814
2,31,75,0,97.358,0.00688,0.000062,0.00315,0.00395,0.00945,0.03787,...,0.02290,0.03866,0.05409,0.019868,17.768,0.51335,0.79928,0.33248,31.967,34.961
3,19,55,0,75.428,0.00705,0.000050,0.00330,0.00300,0.00990,0.01782,...,0.00950,0.01546,0.02424,0.023977,23.276,0.52926,0.65456,0.22484,17.901,26.868
4,34,59,0,157.650,0.00435,0.000038,0.00208,0.00225,0.00623,0.01226,...,0.00661,0.01294,0.01637,0.008735,23.695,0.60103,0.73761,0.17201,25.394,33.662

#### Data Shaping Task 2

Table: Patients

Columns: patient_id, subject_id, age, sex
Constraints: 
patient_id: PRIMARY KEY, AUTO_INCREMENT: This column serves as the primary key and is auto-incremented. It uniquely identifies each patient record.

subject_id: This column presumably stores the subject ID associated with each patient.

age: Stores the age of the patients.

sex: This column likely represents the gender of the patients. It's a numerical representation (e.g., 0 for Male, 1 for Female).

Table: Tests

Columns: test_id, patient_id, test_time, total_UPDRS
Constraints:
test_id: PRIMARY KEY, AUTO_INCREMENT: This column serves as the primary key and is auto-incremented. It uniquely identifies each test record.

patient_id: FOREIGN KEY: This column references the patient_id in the Patients table. It establishes a relationship between the Tests table and the Patients table, ensuring that each test is associated with a patient.

Table: Results

Columns: result_id, test_id, Jitter_percent, Jitter_Abs, Jitter_RAP, Jitter_PPQ5, Jitter_DDP, Shimmer, Shimmer_dB, Shimmer_APQ3, Shimmer_APQ5, Shimmer_APQ11, Shimmer_DDA

Constraints:

result_id: PRIMARY KEY, AUTO_INCREMENT: This column serves as the primary key and is auto-incremented. It uniquely identifies each result record.

test_id: FOREIGN KEY: This column references the test_id in the Tests table. It establishes a relationship between the Results table and the Tests table, ensuring that each result is associated with a test.

Relationships:

Patients to Tests: The Patients table has a one-to-many relationship with the Tests table. One patient can have multiple tests. This relationship is established using the patient_id column in the Tests table, which references the patient_id in the Patients table.

Tests to Results: The Tests table has a one-to-many relationship with the Results table. One test can have multiple results. This relationship is established using the test_id column in the Results table, which references the test_id in the Tests table.

In [ ]:
conn = mysql.connector.connect(
    user='root',
    password='YOUR_PASSWORD_HERE',  # Replace with your actual password
    host='localhost',
    database='ParkinsonsDB'
)

cursor = conn.cursor()


cursor.execute("CREATE DATABASE IF NOT EXISTS ParkinsonsDB")

cursor.execute("USE ParkinsonsDB")

# Create Patients table
cursor.execute("""
    CREATE TABLE IF NOT EXISTS Patients (
        patient_id INT AUTO_INCREMENT PRIMARY KEY,
        subject_id INT,
        age INT,
        sex VARCHAR(10)
    )
""")

cursor.execute("""
    ALTER TABLE Patients
    MODIFY COLUMN sex INTEGER
""")

# Create Tests table
cursor.execute("""
    CREATE TABLE IF NOT EXISTS Tests (
        test_id INT AUTO_INCREMENT PRIMARY KEY,
        patient_id INT,
        test_time FLOAT,
        total_UPDRS FLOAT,
        FOREIGN KEY (patient_id) REFERENCES Patients(patient_id)
    )
""")

# Create Results table 
cursor.execute("""
    CREATE TABLE IF NOT EXISTS Results (
        result_id INT AUTO_INCREMENT PRIMARY KEY,
        test_id INT,
        Jitter_percent FLOAT,
        Jitter_Abs FLOAT,
        Jitter_RAP FLOAT,
        Jitter_PPQ5 FLOAT,
        Jitter_DDP FLOAT,
        Shimmer FLOAT,
        Shimmer_dB FLOAT,
        Shimmer_APQ3 FLOAT,
        Shimmer_APQ5 FLOAT,
        Shimmer_APQ11 FLOAT,
        Shimmer_DDA FLOAT,
        FOREIGN KEY (test_id) REFERENCES Tests(test_id)
    )
""")

conn.commit()
conn.close()

In [ ]:
conn = mysql.connector.connect(
    user='root',
    password='YOUR_PASSWORD_HERE',  # Replace with your actual password
    host='localhost',
    database='ParkinsonsDB'
)

cursor = conn.cursor()
inserted_subject_ids = set()

for index, row in df.iterrows():
    subject_id = row['subject#']
    if subject_id not in inserted_subject_ids:
        cursor.execute("""
            INSERT INTO Patients (subject_id, age, sex)
            VALUES (%s, %s, %s)
        """, (subject_id, row['age'], row['sex']))
        inserted_subject_ids.add(subject_id)

for index, row in df.iterrows():
    cursor.execute("""
        INSERT INTO Tests (patient_id, test_time, total_UPDRS)
        VALUES ((SELECT patient_id FROM Patients WHERE subject_id = %s Limit 1), %s, %s)
    """, (row['subject#'], row['test_time'], row['total_UPDRS']))

for index, row in df.iterrows():
    cursor.execute("""
        INSERT INTO Results (test_id, Jitter_percent, Jitter_Abs, Jitter_RAP, Jitter_PPQ5, Jitter_DDP, Shimmer, Shimmer_dB, Shimmer_APQ3, Shimmer_APQ5, Shimmer_APQ11, Shimmer_DDA)
        SELECT t.test_id, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
        FROM Tests t
        INNER JOIN Patients p ON t.patient_id = p.patient_id
        WHERE p.subject_id = %s
    """, (row['Jitter(%)'], row['Jitter(Abs)'], row['Jitter:RAP'], row['Jitter:PPQ5'], row['Jitter:DDP'], row['Shimmer'], row['Shimmer(dB)'], row['Shimmer:APQ3'], row['Shimmer:APQ5'], row['Shimmer:APQ11'], row['Shimmer:DDA'], row['subject#']))

conn.commit()
conn.close()

In [ ]:
%load_ext sql
connect = 'YOUR_CONNECTION_STRING_HERE/Your ROOT Directory Here'  # Replace with your actual connection string/ Root Directory
%sql $connect

Traceback (most recent call last):
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 3292, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__
    self.__connect()
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect
    with util.safe_reraise():
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\MySQLdb\connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\connection.py", line 70, in set
    cls.current = existing or Connection(descriptor, connect_args, creator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\connection.py", line 55, in __init__
    self.internal_connection = engine.connect()
                               ^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 3268, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 2430, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 3292, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__
    self.__connect()
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect
    with util.safe_reraise():
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\MySQLdb\connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [21]:
%%sql 
SELECT 
    CONSTRAINT_NAME, 
    TABLE_NAME, 
    COLUMN_NAME, 
    REFERENCED_TABLE_NAME, 
    REFERENCED_COLUMN_NAME 
FROM 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE 
    CONSTRAINT_SCHEMA = 'ParkinsonsDB' 
    AND TABLE_NAME IN ('Patients', 'Tests', 'Results');

Traceback (most recent call last):
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\connection.py", line 82, in set
    raise ConnectionError(
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [18]:
%%sql
select * from patients limit 5;

Traceback (most recent call last):
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\connection.py", line 82, in set
    raise ConnectionError(
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [19]:
%%sql
select * from tests limit 5;

Traceback (most recent call last):
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\connection.py", line 82, in set
    raise ConnectionError(
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [20]:
%%sql
select * from results limit 5;

Traceback (most recent call last):
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\dpate\anaconda3\Lib\site-packages\sql\connection.py", line 82, in set
    raise ConnectionError(
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])